project:
  type: website

website:
  title: "Biometrics at the Bush Capital 2025"
  favicon: favicon.ico
  repo-url: https://github.com/IBS-AR/conference2025
  repo-actions: [edit, issue]
  sidebar:
    logo: logo-ibs-ar.svg
  navbar:
    logo: logo-ibs-ar.svg
    left:
      - href: index.qmd
        text: Home
      - program.qmd
      - committee.qmd
      - contact.qmd
    tools:
      - icon: github
        url: https://github.com/IBS-AR/conference2025
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
